[tool.poetry]
name = "blog"
version = "0.1.0"
description = "lessonFlask"
authors = ["nail"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.8"
flask = "2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
